name: Deploy FastAPI to VPS

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  deploy:
    name: Deploy FastAPI to VPS
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fastapi uvicorn

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.10.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to VPS
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << EOF
          cd /redirect  # Change to your application path
          git pull origin main   # Pull the latest changes
          pip install -r requirements.txt  # Install any dependencies
          systemctl restart redirect.service  # Restart FastAPI service
        EOF
